services:
  - type: web
    name: pd-triglav
    env: python
    plan: free # Or your desired plan
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask db upgrade && gunicorn 'app:create_app()'"
    envVars:
      - key: FLASK_APP
        value: app:create_app()
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pd-triglav-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure secret key
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET
        sync: false

databases:
  - name: pd-triglav-db
    databaseName: pd_triglav
    plan: free # Or your desired plan
