"""Add AI content models - HistoricalEvent and NewsItem tables

Revision ID: 090b8ed9ef04
Revises: e419c8494fed
Create Date: 2025-07-26 23:09:44.024780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090b8ed9ef04'
down_revision = 'e419c8494fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('people', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.Enum('FIRST_ASCENT', 'TRAGEDY', 'DISCOVERY', 'ACHIEVEMENT', 'EXPEDITION', name='eventcategory'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'year', name='unique_event_per_date')
    )
    with op.batch_alter_table('historical_events', schema=None) as batch_op:
        batch_op.create_index('idx_historical_events_category', ['category'], unique=False)
        batch_op.create_index('idx_historical_events_date', ['date'], unique=False)
        batch_op.create_index('idx_historical_events_year', ['year'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('SAFETY', 'CONDITIONS', 'ACHIEVEMENTS', 'GEAR', 'EVENTS', name='newscategory'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('news_date', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index('idx_news_items_category', ['category'], unique=False)
        batch_op.create_index('idx_news_items_date', ['news_date'], unique=False)
        batch_op.create_index('idx_news_items_relevance', ['relevance_score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index('idx_news_items_relevance')
        batch_op.drop_index('idx_news_items_date')
        batch_op.drop_index('idx_news_items_category')

    op.drop_table('news_items')
    with op.batch_alter_table('historical_events', schema=None) as batch_op:
        batch_op.drop_index('idx_historical_events_year')
        batch_op.drop_index('idx_historical_events_date')
        batch_op.drop_index('idx_historical_events_category')

    op.drop_table('historical_events')
    # ### end Alembic commands ###
