"""Add url_secondary, methodology and url_methodology fields to HistoricalEvent

Revision ID: 174c924ee90b
Revises: 090b8ed9ef04
Create Date: 2025-07-27 11:28:18.665833

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "174c924ee90b"
down_revision = "090b8ed9ef04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historical_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("url_secondary", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("methodology", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("url_methodology", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historical_events", schema=None) as batch_op:
        batch_op.drop_column("url_methodology")
        batch_op.drop_column("methodology")
        batch_op.drop_column("url_secondary")

    # ### end Alembic commands ###
