"""Add trip discussion feature and notification preferences

Revision ID: 27a3e9e237e8
Revises: 90fecb2360c3
Create Date: 2025-11-07 23:44:25.161597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a3e9e237e8'
down_revision = '90fecb2360c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_discussion', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_participants', schema=None) as batch_op:
        batch_op.drop_column('notify_discussion')

    op.drop_table('trip_discussions')
    # ### end Alembic commands ###
