"""Initial migration with all models

Revision ID: 733a747541d6
Revises: 
Create Date: 2025-07-25 23:13:48.790893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733a747541d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_reports', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_trip_report_per_author', ['trip_id', 'author_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_reports', schema=None) as batch_op:
        batch_op.drop_constraint('unique_trip_report_per_author', type_='unique')

    # ### end Alembic commands ###
