"""Add registration deadline field to trips and update field labels

Revision ID: 90fecb2360c3
Revises: 9d1fdee5241b
Create Date: 2025-08-23 15:08:06.622133

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90fecb2360c3"
down_revision = "9d1fdee5241b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.add_column(sa.Column("registration_deadline", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.drop_column("registration_deadline")

    # ### end Alembic commands ###
