"""Add trip_id to comments for universal commenting system

Revision ID: b3e3fa14507f
Revises: 733a747541d6
Create Date: 2025-07-25 23:38:42.296750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e3fa14507f'
down_revision = '733a747541d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_comments_trip_id', 'trips', ['trip_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_trip_id', type_='foreignkey')
        batch_op.drop_column('trip_id')

    # ### end Alembic commands ###
