"""Add DailyNews model for news caching

Revision ID: df74140f7fce
Revises: 174c924ee90b
Create Date: 2025-07-28 21:54:51.448157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df74140f7fce'
down_revision = '174c924ee90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_date', sa.Date(), nullable=False),
    sa.Column('articles', sa.JSON(), nullable=False),
    sa.Column('fetch_source', sa.String(length=50), nullable=True),
    sa.Column('articles_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_date')
    )
    with op.batch_alter_table('daily_news', schema=None) as batch_op:
        batch_op.create_index('idx_daily_news_date', ['news_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_news', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_news_date')

    op.drop_table('daily_news')
    # ### end Alembic commands ###
